OCR/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('OCR/', include('txystsb.urls')),
]

apps/txystsb/urls.py
from django.urls import path
from .views import index
from .views import upload

app_name='txystsb'
urlpatterns = [
    path('', index),
    path('upload', upload, name='upload'),
]

apps/txystsb/models.py
from django.db import models

# Create your models here.

apps/txystsb/views.py
import requests
import re
import base64
import json

from django.shortcuts import render
from django.http import HttpResponse
from main import Sign, Post, json2text

from txystsb.conf import app_id, secert_id, secert_key, bucket, urls, error_message


# Create your views here.
def index(request):
    '''
    首页
    '''
    return render(request, 'ocr.html')


def upload(request):
    '''
    图片上传
    '''
    s = Sign(app_id, bucket, secert_id, secert_key).__repr__()
    if request.method == 'GET':
        return HttpResponse('ERROR')
    elif request.method == 'POST':
        url_signal = int(request.POST['type'])
        obj = request.FILES.get('image')
        url = urls[url_signal % 8]
        headers = {'Host': 'recognition.image.myqcloud.com',
                   "Authorization": s
                   }

        files = {'appid': (None, app_id),
                 'bucket': (None, bucket),
                 'image': (obj.name, obj.read(), obj.content_type)
            }
        # 附加参数
        if url_signal % 8 == 0:
            files['card_type'] = (url_signal // 8 - 1)
        elif url_signal % 8 == 2:
            files['type'] = (url_signal // 8 - 1)

        # 备用参数
        payload = None 

        # 发送post请求
        post_image = Post(url=url, files=files, payload=payload,
                     headers=headers)
        r = post_image.send_image()
        responseinfo = r.content.decode('utf8')
        s = []
        d = {}
        res = json2text(url_signal % 8, json.loads(responseinfo))
        if type(res[0]) != type(d):
            s = res
        else:
            for k,v in res[0].items():
                s.append('<b>' + k + '</b>' + ' : ' + v + '<br>')
        return HttpResponse(s)# 返回识别信息

templates/ocr.html
<!DOCTYPE html>
<html>
<head>
    <title>图片识别</title>
</head>
<body>
<form action="{% url 'txystsb:upload'  %}" method="post" enctype="multipart/form-data">
    <input type="radio" name="type" value="8">身份证识别（正面）
    <input type="radio" name="type" value="16">身份证识别（反面）
    <input type="radio" name="type" value="1">名片识别
    <input type="radio" name="type" value="10">行驶证识别
    <input type="radio" name="type" value="18">驾驶证识别
    <input type="radio" name="type" value="26">行驶证识别（副页）
    <input type="radio" name="type" value="3">车牌识别
    <input type="radio" name="type" value="4">银行卡识别
    <input type="radio" name="type" value="5">营业执照识别
    <input type="radio" name="type" value="6" checked="checked">通用印刷体识别
    <input type="radio" name="type" value="7">手写体识别
    <br>
    <input type="file" name="image" accept="image/*">
    <input type="submit">
</form>

</body>
</html>